### PR TITLE
Initial setup of `_cul` theme built on top of `_s`

### PR DESCRIPTION
**Pull request by cappadona**
> * Resolves cul-it/wp-cul-main#108

### CODE REVIEW

**Review by manolobevia — COMMENTED** [review]
This is what I have done so far:
- clone this repo
- enable init branch
- run composer install on _cul repo local folder
- run docker-compose up
After the last command I get:
```
/Users/mb863adm/Desktop/_cul
LIB-MB863-MACLAP:_cul mb863adm$ docker compose up
no configuration file provided: not found
LIB-MB863-MACLAP:_cul mb863adm$ docker-compose up
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml
```

**Comment by cappadona** [comment]
@manolobevia This is just the theme....so no Dockerfile here. That will be in a separate repo 😁

**Comment by manolobevia** [comment]
I see. I'll test this "new" theme in my current local WP instance.

**Review by manolobevia — APPROVED** [review]
Theme works for me.

**Pull request merged**
